<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>		
		<RollForward>LatestMajor</RollForward>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>LiteClinic</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<DisableWinUIProgramMain>true</DisableWinUIProgramMain>
		<WinUISDKReferences>false</WinUISDKReferences>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<CsWinRTEnableGenericInterfaces>true</CsWinRTEnableGenericInterfaces>
		<DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>

		<PublishTrimmed>false</PublishTrimmed>
		<SelfContained>true</SelfContained>
		<RunAOTCompilation>false</RunAOTCompilation>
		<PublishReadyToRun>false</PublishReadyToRun>

		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AppxBundle>Never</AppxBundle>
		<GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<AppxBundlePlatforms>x86|x64</AppxBundlePlatforms>
		<PackageCertificateThumbprint>000142B18AC8325621201AFDAF3D4264108CADAF</PackageCertificateThumbprint>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Views\BackupPage.xaml" />
	  <None Remove="Views\CalendarPage.xaml" />
	  <None Remove="Views\ClinicNamePage.xaml" />
	  <None Remove="Views\DoctorDirectoryPage.xaml" />
	  <None Remove="Views\LanguagePage.xaml" />
	  <None Remove="Views\LogsPage.xaml" />
	  <None Remove="Views\MainDbPage.xaml" />
	  <None Remove="Views\NotificationsPage.xaml" />
	  <None Remove="Views\ThemePage.xaml" />
	  <None Remove="Views\WorkingDaysPage.xaml" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
		<PackageReference Include="Syncfusion.Chart.WinUI" Version="34.2.2" />
		<PackageReference Include="Syncfusion.Licensing" Version="34.2.2" />
		<PackageReference Include="System.Diagnostics.EventLog" Version="10.0.10" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
		<PackageReference Include="System.Text.Json" Version="10.0.10" />
		<PackageReference Include="Telegram.Bot" Version="22.10.2.1" />
	</ItemGroup>

	<ItemGroup>
		<Page Update="Views\SplashScreen.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Strings\ar\" />
		<Folder Include="Strings\en-US\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
		<Content Update="Assets\Data\LiteClinic.db">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\france_flag.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\ksa.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\ksa_flag.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\liteclinic.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\LiteClinic_794x530.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\LoginVisual.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\uk.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\uk_flag.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\images\usa_flag.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Profiles\Defaults\default_avatar.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Profiles\Defaults\female_avatar.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Profiles\Defaults\female_avatar_hejab.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="Assets\Profiles\Defaults\male_avatar.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\DoctorDirectoryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\MainDbPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\LogsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\BackupPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\ClinicNamePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\NotificationsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\WorkingDaysPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\CalendarPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\ThemePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\LanguagePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>
	
</Project>